GET https://{{host}}:{{port}}/
Content-Type: application/json

{}

###

POST https://{{host}}:{{port}}/chain/balances
Content-Type: application/json

{
  "address": "UQBSevYG7uExE6wJnWC2adG2SqcjUUqNlmfeTRMFhHT3kWfd",
  "tokenSymbols": [
    "TON",
    "AIOTX"
  ],
  "chain": "ton",
  "network": "testnet",
  "connector": "stonfi"
}

###

POST https://{{host}}:{{port}}/wallet/add
Content-Type: application/json

{
  "chain": "ton",
  "network": "mainnet",
  "privateKey": "sort way burger decrease wild state welcome annual assume mix snack list scorpion improve anxiety fame soap crunch gain foil account knee top soul",
  "address": "",
  "accountId": ""
}

###

POST https://{{host}}:{{port}}/amm/price
Content-Type: application/json

{
  "quote": "USD₮",
  "base": "TON",
  "amount": "1",
  "chain": "ton",
  "network": "mainnet",
  "connector": "stonfi",
  "side": "BUY"
}

###

POST https://{{host}}:{{port}}/amm/trade
Content-Type: application/json

{
  "quote": "USD₮",
  "base": "TON",
  "chain":"ton",
  "connector":"stonfi",
  "network":"mainnet",
  "amount":"0.00123",
  "address":"UQBSevYG7uExE6wJnWC2adG2SqcjUUqNlmfeTRMFhHT3kWfd",
  "side": "BUY"
}

###

POST https://{{host}}:{{port}}/chain/poll
Content-Type: application/json

{
  "txHash": "e3e600ed8f8af27de7294e1fbd471a09f569183875c9ffa35d6bd4556db824df",
  "chain": "ton",
  "network": "mainnet"
}

###


POST https://api.ston.fi/v1/swap/simulate?ask_address=EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs&offer_address=EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c&slippage_tolerance=0.01&units=12300000
Content-Type: application/json

{
}

###

